version: "3.9"

services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vite-react-app:latest
    container_name: vite-react-container
    ports:
      - "4174:4174"
    restart: unless-stopped
